[2025-07-24T14:18:25.409+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T14:18:25.453+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.stage_events scheduled__2025-07-23T00:00:00+00:00 [queued]>
[2025-07-24T14:18:25.469+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.stage_events scheduled__2025-07-23T00:00:00+00:00 [queued]>
[2025-07-24T14:18:25.470+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-07-24T14:18:25.499+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_events> on 2025-07-23 00:00:00+00:00
[2025-07-24T14:18:25.509+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'stage_events', 'scheduled__2025-07-23T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmp2bj5i1ro']
[2025-07-24T14:18:25.516+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask stage_events
[2025-07-24T14:18:25.516+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=172) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T14:18:25.517+0000] {standard_task_runner.py:64} INFO - Started process 175 to run task
[2025-07-24T14:18:25.545+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T14:18:25.630+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.stage_events scheduled__2025-07-23T00:00:00+00:00 [running]> on host da6b6b72382b
[2025-07-24T14:18:25.814+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='stage_events' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-23T00:00:00+00:00'
[2025-07-24T14:18:25.821+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T14:18:25.916+0000] {logging_mixin.py:188} INFO - tổng số file json tìm được là 0
[2025-07-24T14:18:33.992+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T14:18:33.993+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 107, in load_log_data_to_table
    connect = psycopg2.connect(**conn_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "hainam" to address: Temporary failure in name resolution

[2025-07-24T14:18:34.314+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=tunestream_etl, task_id=stage_events, run_id=scheduled__2025-07-23T00:00:00+00:00, execution_date=20250723T000000, start_date=20250724T141825, end_date=20250724T141834
[2025-07-24T14:18:34.363+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 38 for task stage_events (could not translate host name "hainam" to address: Temporary failure in name resolution
; 175)
[2025-07-24T14:18:34.397+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T14:18:34.456+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T14:18:34.473+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
