[2025-07-24T16:51:15.770+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T16:51:15.802+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_time_dim_star manual__2025-07-24T16:50:52.440427+00:00 [queued]>
[2025-07-24T16:51:15.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_time_dim_star manual__2025-07-24T16:50:52.440427+00:00 [queued]>
[2025-07-24T16:51:15.815+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T16:51:15.839+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_time_dim_star> on 2025-07-24 16:50:52.440427+00:00
[2025-07-24T16:51:15.847+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_time_dim_star', 'manual__2025-07-24T16:50:52.440427+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmpxka6gray']
[2025-07-24T16:51:15.851+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask load_time_dim_star
[2025-07-24T16:51:15.859+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8059) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T16:51:15.860+0000] {standard_task_runner.py:64} INFO - Started process 8062 to run task
[2025-07-24T16:51:15.870+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T16:51:15.918+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_time_dim_star manual__2025-07-24T16:50:52.440427+00:00 [running]> on host da6b6b72382b
[2025-07-24T16:51:16.034+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_time_dim_star' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T16:50:52.440427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T16:50:52.440427+00:00'
[2025-07-24T16:51:16.035+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T16:51:16.143+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T16:51:16.144+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 182, in _run
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column "artist_id" of relation "artists" does not exist
LINE 2:         INSERT INTO artists (artist_id, name, location, lati...
                                     ^

[2025-07-24T16:51:16.197+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_time_dim_star, run_id=manual__2025-07-24T16:50:52.440427+00:00, execution_date=20250724T165052, start_date=20250724T165115, end_date=20250724T165116
[2025-07-24T16:51:16.215+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task load_time_dim_star (column "artist_id" of relation "artists" does not exist
LINE 2:         INSERT INTO artists (artist_id, name, location, lati...
                                     ^
; 8062)
[2025-07-24T16:51:16.237+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T16:51:16.269+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T16:51:16.278+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
