[2025-07-24T17:12:18.374+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T17:12:18.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_user_dim_table manual__2025-07-24T17:11:55.182686+00:00 [queued]>
[2025-07-24T17:12:18.414+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_user_dim_table manual__2025-07-24T17:11:55.182686+00:00 [queued]>
[2025-07-24T17:12:18.415+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T17:12:18.430+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_user_dim_table> on 2025-07-24 17:11:55.182686+00:00
[2025-07-24T17:12:18.441+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=9279) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T17:12:18.439+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_user_dim_table', 'manual__2025-07-24T17:11:55.182686+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmplq3cf9pt']
[2025-07-24T17:12:18.442+0000] {standard_task_runner.py:64} INFO - Started process 9284 to run task
[2025-07-24T17:12:18.442+0000] {standard_task_runner.py:91} INFO - Job 107: Subtask load_user_dim_table
[2025-07-24T17:12:18.464+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T17:12:18.550+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_user_dim_table manual__2025-07-24T17:11:55.182686+00:00 [running]> on host da6b6b72382b
[2025-07-24T17:12:18.644+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_user_dim_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T17:11:55.182686+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T17:11:55.182686+00:00'
[2025-07-24T17:12:18.647+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T17:12:18.735+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T17:12:18.737+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 195, in _run
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column excluded.firstname does not exist
LINE 7:         SET firstname = EXCLUDED.firstname,
                                ^
HINT:  Perhaps you meant to reference the column "excluded.first_name".

[2025-07-24T17:12:18.752+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_user_dim_table, run_id=manual__2025-07-24T17:11:55.182686+00:00, execution_date=20250724T171155, start_date=20250724T171218, end_date=20250724T171218
[2025-07-24T17:12:18.767+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 107 for task load_user_dim_table (column excluded.firstname does not exist
LINE 7:         SET firstname = EXCLUDED.firstname,
                                ^
HINT:  Perhaps you meant to reference the column "excluded.first_name".
; 9284)
[2025-07-24T17:12:18.777+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T17:12:18.787+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
