[2025-07-24T16:59:30.359+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T16:59:30.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.data_quality_check manual__2025-07-24T16:50:52.440427+00:00 [queued]>
[2025-07-24T16:59:30.398+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.data_quality_check manual__2025-07-24T16:50:52.440427+00:00 [queued]>
[2025-07-24T16:59:30.398+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T16:59:30.414+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_quality_check> on 2025-07-24 16:50:52.440427+00:00
[2025-07-24T16:59:30.421+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'data_quality_check', 'manual__2025-07-24T16:50:52.440427+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmptfuykex6']
[2025-07-24T16:59:30.423+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask data_quality_check
[2025-07-24T16:59:30.439+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T16:59:30.439+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8549) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T16:59:30.440+0000] {standard_task_runner.py:64} INFO - Started process 8550 to run task
[2025-07-24T16:59:30.507+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.data_quality_check manual__2025-07-24T16:50:52.440427+00:00 [running]> on host da6b6b72382b
[2025-07-24T16:59:30.598+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='data_quality_check' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T16:50:52.440427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T16:50:52.440427+00:00'
[2025-07-24T16:59:30.599+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T16:59:30.676+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T16:59:30.678+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 219, in run_check_quality_data
    for table, pk in tables_info:
        ^^^^^^^^^
ValueError: too many values to unpack (expected 2)
[2025-07-24T16:59:30.711+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=data_quality_check, run_id=manual__2025-07-24T16:50:52.440427+00:00, execution_date=20250724T165052, start_date=20250724T165930, end_date=20250724T165930
[2025-07-24T16:59:30.729+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 84 for task data_quality_check (too many values to unpack (expected 2); 8550)
[2025-07-24T16:59:30.775+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T16:59:30.802+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T16:59:30.807+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
