[2025-07-24T17:03:31.085+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T17:03:31.124+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T17:03:06.116098+00:00 [queued]>
[2025-07-24T17:03:31.140+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T17:03:06.116098+00:00 [queued]>
[2025-07-24T17:03:31.142+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T17:03:31.170+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_time_dim> on 2025-07-24 17:03:06.116098+00:00
[2025-07-24T17:03:31.212+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8756) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T17:03:31.209+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_time_dim', 'manual__2025-07-24T17:03:06.116098+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmp4j6kbqzi']
[2025-07-24T17:03:31.213+0000] {standard_task_runner.py:64} INFO - Started process 8767 to run task
[2025-07-24T17:03:31.213+0000] {standard_task_runner.py:91} INFO - Job 89: Subtask load_time_dim
[2025-07-24T17:03:31.281+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T17:03:31.346+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T17:03:06.116098+00:00 [running]> on host da6b6b72382b
[2025-07-24T17:03:31.459+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_time_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T17:03:06.116098+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T17:03:06.116098+00:00'
[2025-07-24T17:03:31.461+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T17:03:31.609+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T17:03:31.614+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 182, in _run
    cur.execute(query)
psycopg2.errors.InvalidParameterValue: unit "dayofweek" not recognized for type timestamp without time zone

[2025-07-24T17:03:31.695+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_time_dim, run_id=manual__2025-07-24T17:03:06.116098+00:00, execution_date=20250724T170306, start_date=20250724T170331, end_date=20250724T170331
[2025-07-24T17:03:31.726+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 89 for task load_time_dim (unit "dayofweek" not recognized for type timestamp without time zone
; 8767)
[2025-07-24T17:03:31.760+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T17:03:31.776+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
