[2025-07-24T16:51:15.764+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T16:51:15.794+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T16:50:52.440427+00:00 [queued]>
[2025-07-24T16:51:15.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T16:50:52.440427+00:00 [queued]>
[2025-07-24T16:51:15.806+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T16:51:15.824+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_time_dim> on 2025-07-24 16:50:52.440427+00:00
[2025-07-24T16:51:15.834+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_time_dim', 'manual__2025-07-24T16:50:52.440427+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmpaquis13r']
[2025-07-24T16:51:15.837+0000] {standard_task_runner.py:91} INFO - Job 76: Subtask load_time_dim
[2025-07-24T16:51:15.854+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=8056) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T16:51:15.855+0000] {standard_task_runner.py:64} INFO - Started process 8061 to run task
[2025-07-24T16:51:15.858+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T16:51:15.917+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T16:50:52.440427+00:00 [running]> on host da6b6b72382b
[2025-07-24T16:51:16.043+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_time_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T16:50:52.440427+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T16:50:52.440427+00:00'
[2025-07-24T16:51:16.045+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T16:51:16.209+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T16:51:16.212+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 182, in _run
    cur.execute(query)
psycopg2.errors.InvalidParameterValue: unit "dayofweek" not recognized for type timestamp without time zone

[2025-07-24T16:51:16.246+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_time_dim, run_id=manual__2025-07-24T16:50:52.440427+00:00, execution_date=20250724T165052, start_date=20250724T165115, end_date=20250724T165116
[2025-07-24T16:51:16.275+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 76 for task load_time_dim (unit "dayofweek" not recognized for type timestamp without time zone
; 8061)
[2025-07-24T16:51:16.317+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T16:51:16.360+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T16:51:16.364+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
