[2025-07-24T16:42:13.998+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T16:42:14.017+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_songplays_face_table manual__2025-07-24T16:41:51.163845+00:00 [queued]>
[2025-07-24T16:42:14.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_songplays_face_table manual__2025-07-24T16:41:51.163845+00:00 [queued]>
[2025-07-24T16:42:14.026+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T16:42:14.040+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_songplays_face_table> on 2025-07-24 16:41:51.163845+00:00
[2025-07-24T16:42:14.046+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=7554) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T16:42:14.047+0000] {standard_task_runner.py:64} INFO - Started process 7555 to run task
[2025-07-24T16:42:14.046+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_songplays_face_table', 'manual__2025-07-24T16:41:51.163845+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmpcdlqajpa']
[2025-07-24T16:42:14.048+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask load_songplays_face_table
[2025-07-24T16:42:14.062+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T16:42:14.094+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_songplays_face_table manual__2025-07-24T16:41:51.163845+00:00 [running]> on host da6b6b72382b
[2025-07-24T16:42:14.204+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_songplays_face_table' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T16:41:51.163845+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T16:41:51.163845+00:00'
[2025-07-24T16:42:14.205+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T16:42:14.272+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T16:42:14.274+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 169, in _run
    cur.execute(query)
psycopg2.errors.UndefinedColumn: column "songplay_id" of relation "songplays" does not exist
LINE 2:         INSERT INTO songplays(songplay_id, start_time, useri...
                                      ^

[2025-07-24T16:42:14.291+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_songplays_face_table, run_id=manual__2025-07-24T16:41:51.163845+00:00, execution_date=20250724T164151, start_date=20250724T164214, end_date=20250724T164214
[2025-07-24T16:42:14.304+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 65 for task load_songplays_face_table (column "songplay_id" of relation "songplays" does not exist
LINE 2:         INSERT INTO songplays(songplay_id, start_time, useri...
                                      ^
; 7555)
[2025-07-24T16:42:14.340+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T16:42:14.358+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T16:42:14.362+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
