[2025-07-22T09:51:41.690+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T09:51:41.893+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [queued]>
[2025-07-22T09:51:41.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [queued]>
[2025-07-22T09:51:41.928+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 4
[2025-07-22T09:51:42.028+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_songs> on 2025-07-22 09:11:27.349803+00:00
[2025-07-22T09:51:42.071+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'stage_songs', 'manual__2025-07-22T09:11:27.349803+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmpzdedn4nz']
[2025-07-22T09:51:42.074+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=404) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T09:51:42.076+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask stage_songs
[2025-07-22T09:51:42.076+0000] {standard_task_runner.py:64} INFO - Started process 405 to run task
[2025-07-22T09:51:42.148+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-22T09:51:42.277+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [running]> on host 2ad5d09a42d7
[2025-07-22T09:51:42.908+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T09:11:27.349803+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T09:11:27.349803+00:00'
[2025-07-22T09:51:42.923+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T09:51:43.227+0000] {logging_mixin.py:188} INFO - tổng số file json tìm được là 0
[2025-07-22T09:51:51.248+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T09:51:51.253+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 29, in load_song_data_to_table
    connect = psycopg2.connect(**conn_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "hainam" to address: Temporary failure in name resolution

[2025-07-22T09:51:51.319+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=tunestream_etl, task_id=stage_songs, run_id=manual__2025-07-22T09:11:27.349803+00:00, execution_date=20250722T091127, start_date=20250722T095141, end_date=20250722T095151
[2025-07-22T09:51:51.374+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task stage_songs (could not translate host name "hainam" to address: Temporary failure in name resolution
; 405)
[2025-07-22T09:51:51.456+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-22T09:51:51.528+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T09:51:51.546+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
