[2025-07-22T09:16:44.255+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-22T09:16:44.334+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [queued]>
[2025-07-22T09:16:44.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [queued]>
[2025-07-22T09:16:44.348+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2025-07-22T09:16:44.379+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): stage_songs> on 2025-07-22 09:11:27.349803+00:00
[2025-07-22T09:16:44.388+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'stage_songs', 'manual__2025-07-22T09:11:27.349803+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmpn3z7s2zp']
[2025-07-22T09:16:44.389+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=7766) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-22T09:16:44.390+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask stage_songs
[2025-07-22T09:16:44.391+0000] {standard_task_runner.py:64} INFO - Started process 7767 to run task
[2025-07-22T09:16:44.416+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-22T09:16:44.464+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.stage_songs manual__2025-07-22T09:11:27.349803+00:00 [running]> on host 7b3eb14378b0
[2025-07-22T09:16:44.599+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='stage_songs' AIRFLOW_CTX_EXECUTION_DATE='2025-07-22T09:11:27.349803+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-22T09:11:27.349803+00:00'
[2025-07-22T09:16:44.600+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-22T09:16:44.650+0000] {logging_mixin.py:188} INFO - tổng số file json tìm được là 0
[2025-07-22T09:16:52.697+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-22T09:16:52.699+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 28, in load_song_data_to_table
    connect = psycopg2.connect(**conn_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "hainam" to address: Temporary failure in name resolution

[2025-07-22T09:16:52.747+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=stage_songs, run_id=manual__2025-07-22T09:11:27.349803+00:00, execution_date=20250722T091127, start_date=20250722T091644, end_date=20250722T091652
[2025-07-22T09:16:52.777+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task stage_songs (could not translate host name "hainam" to address: Temporary failure in name resolution
; 7767)
[2025-07-22T09:16:52.807+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-22T09:16:52.848+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-22T09:16:52.853+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
