[2025-07-24T17:08:47.139+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-24T17:08:47.167+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T17:08:24.333160+00:00 [queued]>
[2025-07-24T17:08:47.177+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T17:08:24.333160+00:00 [queued]>
[2025-07-24T17:08:47.178+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2025-07-24T17:08:47.196+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_time_dim> on 2025-07-24 17:08:24.333160+00:00
[2025-07-24T17:08:47.205+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tunestream_etl', 'load_time_dim', 'manual__2025-07-24T17:08:24.333160+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/tunestream_etl_dag.py', '--cfg-path', '/tmp/tmp8i3sblba']
[2025-07-24T17:08:47.207+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask load_time_dim
[2025-07-24T17:08:47.212+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=9057) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-24T17:08:47.213+0000] {standard_task_runner.py:64} INFO - Started process 9062 to run task
[2025-07-24T17:08:47.245+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-24T17:08:47.376+0000] {task_command.py:426} INFO - Running <TaskInstance: tunestream_etl.load_time_dim manual__2025-07-24T17:08:24.333160+00:00 [running]> on host da6b6b72382b
[2025-07-24T17:08:47.548+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='NamTH91' AIRFLOW_CTX_DAG_ID='tunestream_etl' AIRFLOW_CTX_TASK_ID='load_time_dim' AIRFLOW_CTX_EXECUTION_DATE='2025-07-24T17:08:24.333160+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-24T17:08:24.333160+00:00'
[2025-07-24T17:08:47.549+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-24T17:08:47.682+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-24T17:08:47.688+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tunestream_etl_dag.py", line 184, in _run
    cur.execute(query)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "time_pkey"
DETAIL:  Key (start_time)=(2018-11-14 04:53:36) already exists.

[2025-07-24T17:08:47.721+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=tunestream_etl, task_id=load_time_dim, run_id=manual__2025-07-24T17:08:24.333160+00:00, execution_date=20250724T170824, start_date=20250724T170847, end_date=20250724T170847
[2025-07-24T17:08:47.742+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 99 for task load_time_dim (duplicate key value violates unique constraint "time_pkey"
DETAIL:  Key (start_time)=(2018-11-14 04:53:36) already exists.
; 9062)
[2025-07-24T17:08:47.788+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-07-24T17:08:47.813+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-24T17:08:47.817+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
